create GENERATOR GEN_PAISES;
set GENERATOR GEN_PAISES to 0;

create GENERATOR GEN_DEPARTAMENTOS;
set GENERATOR GEN_DEPARTAMENTOS to 0;

create GENERATOR GEN_CORES;
set GENERATOR GEN_CORES to 0;

create GENERATOR GEN_COLECOES;
set GENERATOR GEN_COLECOES to 0;

create GENERATOR GEN_GRUPOS_ROUPAS;
set GENERATOR GEN_COLECOES to 0;

create GENERATOR GEN_MARCAS;
set GENERATOR GEN_MARCAS to 0;

create GENERATOR GEN_SIGLA_TAMANHOS;
set GENERATOR GEN_SIGLA_TAMANHOS to 0;

create GENERATOR GEN_FORMAS_PAGAMENTOS;
set GENERATOR GEN_FORMAS_PAGAMENTOS to 0;

create GENERATOR GEN_TIPOS_CONTATOS;
set GENERATOR GEN_TIPOS_CONTATOS to 0;

create GENERATOR GEN_ESTADOS;
set GENERATOR GEN_ESTADOS to 0;

create GENERATOR GEN_CIDADES;
set GENERATOR GEN_CIDADES to 0;

create GENERATOR GEN_CARGOS;
set GENERATOR GEN_CARGOS to 0;

create GENERATOR GEN_CONDICOES_PAGAMENTOS;
set GENERATOR GEN_CONDICOES_PAGAMENTOS to 0;

create GENERATOR GEN_FORNECEDORES;
set GENERATOR GEN_FORNECEDORES to 0;

create GENERATOR GEN_FUNCIONARIOS;
set GENERATOR GEN_FUNCIONARIOS to 0;

create GENERATOR GEN_CLIENTES;
set GENERATOR GEN_CLIENTES to 0;

create GENERATOR GEN_ROUPAS;
set GENERATOR GEN_ROUPAS to 0;