create table PAISES(
    codPais integer not null primary key,
    pais varchar(50) not null,
    ddi varchar(4),
    sigla varchar(3) not null,
    moeda varchar(3),
    dataCad timestamp,
    ultAlt timestamp,
    codUsuAlt integer
);

create table DEPARTAMENTOS(
    codDepartamento integer not null primary key,
    depatamento varchar(80) not null,
    dataCad timestamp,
    ultAlt timestamp,
    codUsuAlt integer
);

CREATE TABLE CORES (
    CODCOR   INTEGER NOT NULL PRIMARY KEY,
    COR      VARCHAR(80) NOT NULL,
    DATACAD  TIMESTAMP,
    ULTALT   TIMESTAMP,
    CODUSUALT  INTEGER
);

CREATE TABLE COLECOES (
    CODCOLECAO  INTEGER NOT NULL PRIMARY KEY,
    COLECAO     VARCHAR(80) NOT NULL,
    DATACAD     TIMESTAMP,
    ULTALT      TIMESTAMP,
    CODUSUALT   INTEGER
);

CREATE TABLE GRUPOS_ROUPAS (
    CODGRUPO    INTEGER NOT NULL PRIMARY KEY,
    GRUPOROUPA  VARCHAR(80) NOT NULL,
    DATACAD     TIMESTAMP,
    ULTALT      TIMESTAMP,
    CODUSUALT   INTEGER
);

CREATE TABLE MARCAS (
    CODMARCA  INTEGER NOT NULL PRIMARY KEY,
    MARCA     VARCHAR(80) NOT NULL,
    DATACAD   TIMESTAMP,
    ULTALT    TIMESTAMP,
    CODUSU    INTEGER
);

CREATE TABLE SIGLA_TAMANHOS (
    CODSIGLA     INTEGER NOT NULL PRIMARY KEY,
    SIGLA        VARCHAR(3) NOT NULL,
    ALTURA       VARCHAR(4),
    LARGURA      VARCHAR(4),
    COMPRIMENTO  VARCHAR(4),
    DATACAD      TIMESTAMP,
    ULTALT       TIMESTAMP,
    CODUSUALT    INTEGER
);

CREATE TABLE FORMAS_PAGAMENTOS (
    CODFORMA   INTEGER NOT NULL PRIMARY KEY,
    FORMA      VARCHAR(80) NOT NULL,
    DATACAD    TIMESTAMP,
    ULTALT     TIMESTAMP,
    CODUSUALT  INTEGER
);

CREATE TABLE TIPOS_CONTATOS (
    CODTIPO      INTEGER NOT NULL PRIMARY KEY,
    TIPOCONTATO  VARCHAR(80) NOT NULL,
    DATACAD      TIMESTAMP,
    ULTALT       TIMESTAMP,
    CODUSU       INTEGER
);

CREATE TABLE ESTADOS (
    CODESTADO  INTEGER NOT NULL PRIMARY KEY,
    ESTADO     VARCHAR(80) NOT NULL,
    UF         VARCHAR(3),
    DATACAD    TIMESTAMP,
    ULTALT     TIMESTAMP,
    CODUSU     INTEGER,
    CODPAIS    INTEGER NOT NULL,
    FOREIGN KEY (CODPAIS) REFERENCES PAISES(CODPAIS)
);

CREATE TABLE CIDADES (
    CODCIDADE  INTEGER NOT NULL PRIMARY KEY,
    CIDADE     VARCHAR(50) NOT NULL,
    SIGLA      VARCHAR(3),
    DDD        VARCHAR(3) NOT NULL,
    DATACAD    TIMESTAMP,
    ULTALT     TIMESTAMP,
    CODUSU     INTEGER,
    CODESTADO  INTEGER NOT NULL,
    FOREIGN KEY (CODESTADO) REFERENCES ESTADOS(CODESTADO)
);

CREATE TABLE CARGOS (
    CODCARGO         INTEGER NOT NULL PRIMARY KEY,
    CARGO            VARCHAR(80) NOT NULL,
    CODDEPARTAMENTO  INTEGER NOT NULL,
    DATACAD          TIMESTAMP,
    ULTALT           TIMESTAMP,
    CODUSU           INTEGER,
    FOREIGN kEY (CODDEPARTAMENTO) REFERENCES DEPARTAMENTOS(CODDEPARTAMENTO)
);

CREATE TABLE CONDICOES_PAGAMENTOS (
    CODCONDICAO  INTEGER NOT NULL,
    CONDICAO     VARCHAR(80) NOT NULL,
    DATACAD      TIMESTAMP,
    ULTALT       TIMESTAMP,
    CODUSU       INTEGER,
    PARCELAS     INTEGER,
    JUROS        FLOAT,
    DESCONTO     FLOAT,
    MULTA        FLOAT,
    CODFORMA     INTEGER,
    DIAS         INTEGER,
    PORCENTAGEM  FLOAT
);

ALTER TABLE CONDICOES_PAGAMENTOS ADD CONSTRAINT PK_CONDICOES_PAGAMENTOS PRIMARY KEY (CODCONDICAO);
ALTER TABLE CONDICOES_PAGAMENTOS ADD CONSTRAINT FK_CONDICOES_PAGAMENTOS_1 FOREIGN KEY (CODFORMA) REFERENCES FORMAS_PAGAMENTOS (CODFORMA);

CREATE TABLE FORNECEDORES (
    CODFORN            INTEGER NOT NULL,
    DATACAD            TIMESTAMP,
    ULTALT             TIMESTAMP,
    CODUSU             INTEGER,
    NOME_RAZAO_SOCIAL  VARCHAR(80),
    TIPO_FORN          VARCHAR(50),
    APELIDO_FANTASIA   VARCHAR(80),
    ENDERECO           VARCHAR(60),
    NUMERO             VARCHAR(8),
    COMPLEMENTO        VARCHAR(60),
    BAIRRO             VARCHAR(60),
    CEP                VARCHAR(8),
    CODCIDADE          INTEGER,
    CODCONTATO         INTEGER,
    CONTATO_AUX1       VARCHAR(50),
    CONTATO_AUX2       VARCHAR(50),
    CNPJ_CPF           VARCHAR(14),
    IE_RG              VARCHAR(14),
    CODCONDICAO        INTEGER
);

ALTER TABLE FORNECEDORES ADD CONSTRAINT PK_FORNECEDORES PRIMARY KEY (CODFORN);
ALTER TABLE FORNECEDORES ADD CONSTRAINT FK_FORNECEDORES_1 FOREIGN KEY (CODCIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE FORNECEDORES ADD CONSTRAINT FK_FORNECEDORES_2 FOREIGN KEY (CODCONTATO) REFERENCES TIPOS_CONTATOS (CODTIPO);
ALTER TABLE FORNECEDORES ADD CONSTRAINT FK_FORNECEDORES_3 FOREIGN KEY (CODCONDICAO) REFERENCES CONDICOES_PAGAMENTOS (CODCONDICAO);

CREATE TABLE FUNCIONARIOS (
    CODFUNC        INTEGER NOT NULL,
    DATACAD        TIMESTAMP,
    ULTALT         TIMESTAMP,
    CODUSU         INTEGER,
    FUNCIONARIO    VARCHAR(80) NOT NULL,
    SEXO           VARCHAR(1),
    ENDERECO       VARCHAR(60),
    NUMERO         VARCHAR(8),
    COMPLEMENTO    VARCHAR(60),
    BAIRRO         VARCHAR(60),
    CEP            VARCHAR(10),
    CODCIDADE      INTEGER,
    CODCONTATO     INTEGER,
    CONTATO_AUX1   VARCHAR(50),
    CONTATO_AUX2   VARCHAR(50),
    CPF            VARCHAR(14) NOT NULL,
    RG             VARCHAR(14),
    DATA_NASC      TIMESTAMP,
    CODCARGO       INTEGER,
    DATA_ADMISSAO  TIMESTAMP,
    DATA_DEMISSAO  TIMESTAMP,
    SALARIO        FLOAT,
    COMISSAO       FLOAT,
    OBS            VARCHAR(250)
);

ALTER TABLE FUNCIONARIOS ADD CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (CODFUNC);
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FK_FUNCIONARIOS_1 FOREIGN KEY (CODCIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FK_FUNCIONARIOS_2 FOREIGN KEY (CODCONTATO) REFERENCES TIPOS_CONTATOS (CODTIPO);
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FK_FUNCIONARIOS_3 FOREIGN KEY (CODCARGO) REFERENCES CARGOS (CODCARGO);

CREATE TABLE CLIENTES (
    CODCLIENTE      INTEGER NOT NULL,
    DATACAD         TIMESTAMP,
    ULTALT          TIMESTAMP,
    CODUSU          INTEGER,
    RAZAO_SOCIAL    VARCHAR(80) NOT NULL,
    FANTASIA        VARCHAR(80) NOT NULL,
    ENDERECO        VARCHAR(60),
    NUMERO          VARCHAR(8),
    COMPLEMENTO     VARCHAR(60),
    BAIRRO          VARCHAR(60),
    CEP             VARCHAR(10),
    CODCIDADE       INTEGER NOT NULL,
    CODCONTATO      INTEGER,
    CONTATO_AUX1    VARCHAR(50),
    CONTATO_AUX2    VARCHAR(50),
    CODFUNC         INTEGER,
    CNPJ            VARCHAR(14) NOT NULL,
    IE              VARCHAR(14),
    LIMITE_CREDITO  FLOAT,
    CODCONDICAO     INTEGER,
    OBS             VARCHAR(250)
);

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (CODCLIENTE);
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_1 FOREIGN KEY (CODCIDADE) REFERENCES CIDADES (CODCIDADE);
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_2 FOREIGN KEY (CODCONTATO) REFERENCES TIPOS_CONTATOS (CODTIPO);
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_3 FOREIGN KEY (CODCONDICAO) REFERENCES CONDICOES_PAGAMENTOS (CODCONDICAO);
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_4 FOREIGN KEY (CODFUNC) REFERENCES FUNCIONARIOS (CODFUNC);

CREATE TABLE ROUPAS (
    COD_ROUPA        INTEGER NOT NULL,
    DATACAD          TIMESTAMP,
    ULTALT           TIMESTAMP,
    CODUSU           INTEGER,
    DESCRICAO_ROUPA  VARCHAR(80) NOT NULL,
    COD_BARRA        VARCHAR(50),
    REFERENCIA       VARCHAR(50),
    CODGRUPOROUPA    INTEGER,
    CODMARCA         INTEGER,
    VALOR_CUSTO      FLOAT,
    LUCRO            FLOAT,
    VALOR_VENDA      FLOAT,
    CODCOR           INTEGER,
    CODTAMANHO       INTEGER,
    CODFORNECEDOR    INTEGER,
    CODCOLECAO       INTEGER,
    OBS              VARCHAR(250)
);

ALTER TABLE ROUPAS ADD CONSTRAINT PK_ROUPAS PRIMARY KEY (COD_ROUPA);
ALTER TABLE ROUPAS ADD CONSTRAINT FK_ROUPAS_1 FOREIGN KEY (CODGRUPOROUPA) REFERENCES GRUPOS_ROUPAS (CODGRUPO);
ALTER TABLE ROUPAS ADD CONSTRAINT FK_ROUPAS_2 FOREIGN KEY (CODCOR) REFERENCES CORES (CODCOR);
ALTER TABLE ROUPAS ADD CONSTRAINT FK_ROUPAS_3 FOREIGN KEY (CODTAMANHO) REFERENCES SIGLA_TAMANHOS (CODSIGLA);
ALTER TABLE ROUPAS ADD CONSTRAINT FK_ROUPAS_4 FOREIGN KEY (CODFORNECEDOR) REFERENCES FORNECEDORES (CODFORN);
ALTER TABLE ROUPAS ADD CONSTRAINT FK_ROUPAS_5 FOREIGN KEY (CODCOLECAO) REFERENCES COLECOES (CODCOLECAO);