set term ^;

CREATE OR ALTER TRIGGER PAISES_BI FOR PAISES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (NEW.CODPAIS = 0) THEN
        new.CODPAIS = GEN_ID(GEN_PAISES, 1);
END ^
set term ; ^

set term ^;

CREATE OR ALTER TRIGGER DEPARTAMENTOS_BI FOR DEPARTAMENTOS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (NEW.CODDEPARTAMENTO = 0) THEN
        new.CODDEPARTAMENTO = GEN_ID(GEN_DEPARTAMENTOS, 1);
END ^

set term ; ^

CREATE OR ALTER TRIGGER CORES_BI FOR CORES
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (NEW.CODCOR = 0) THEN
        new.CODCOR = GEN_ID(GEN_CORES, 1);
END ^
set term ; ^

CREATE OR ALTER TRIGGER COLECOES_BI FOR COLECOES
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (NEW.CODCOLECAO = 0) THEN
        new.CODCOLECAO = GEN_ID(gen_colecoes, 1);
end

CREATE OR ALTER TRIGGER GRUPOS_ROUPAS_BI FOR GRUPOS_ROUPAS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (NEW.codgrupo = 0) THEN
        new.codgrupo = GEN_ID(gen_grupos_roupas, 1);
end

CREATE OR ALTER TRIGGER MARCAS_BI FOR MARCAS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (NEW.codmarca = 0) THEN
        new.codmarca = GEN_ID(gen_marcas, 1);
end

CREATE OR ALTER TRIGGER SIGLA_TAMANHOS_BI FOR SIGLA_TAMANHOS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (NEW.codsigla = 0) THEN
        new.codsigla = GEN_ID(gen_sigla_tamanhos, 1);
end

CREATE OR ALTER TRIGGER FORMAS_PAGAMENTOS_BI FOR FORMAS_PAGAMENTOS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (NEW.codforma = 0) THEN
        new.codforma = GEN_ID(gen_formas_pagamentos, 1);
end

CREATE OR ALTER TRIGGER TIPOS_CONTATOS_BI FOR TIPOS_CONTATOS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (NEW.codtipo = 0) THEN
        new.codtipo = GEN_ID(gen_tipos_contatos, 1);
end

CREATE OR ALTER TRIGGER ESTADOS_BI FOR ESTADOS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (NEW.codestado = 0) THEN
        new.codestado = GEN_ID(gen_estados, 1);
end

CREATE OR ALTER TRIGGER CIDADES_BI FOR CIDADES
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (NEW.codcidade = 0) THEN
        new.codcidade = GEN_ID(gen_cidades, 1);
end

CREATE OR ALTER TRIGGER CARGOS_BI FOR CARGOS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (NEW.codcargo = 0) THEN
        new.codcargo = GEN_ID(gen_cargos, 1);
end