create GENERATOR GEN_PAISES;
set GENERATOR GEN_PAISES to 0;

create GENERATOR GEN_ESTADOS;
set GENERATOR GEN_ESTADOS to 0;

create GENERATOR GEN_DEPARTAMENTOS;
set GENERATOR GEN_DEPARTAMENTOS to 0;

create GENERATOR GEN_CORES;
set GENERATOR GEN_CORES to 0;

create GENERATOR GEN_COLECOES;
set GENERATOR GEN_COLECOES to 0;

create GENERATOR GEN_GRUPOS_ROUPAS;
set GENERATOR GEN_COLECOES to 0;